version: "3.8"

services:
  base_oauth_pg:
    container_name: base_oauth_pg
    image: postgres:alpine
    env_file: .env
    volumes:
      - base-oauth-pg:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - base-oauth

  base_oauth:
    container_name: base_oauth
    build:
      context: ./
      dockerfile: infra/images/local/api.Dockerfile
    volumes:
      - .:/home/app
    networks:
      - base-oauth
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    # command:
    #   - "python"
    #   - "-m"
    #   - "debugpy"
    #   - "--listen"
    #   - "0.0.0.0:8001"
    #   - "base-oauth.py"
    ports:
      - 8888:8888
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.localhost`)

  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=boy
      - traefik.http.routers.reverse-proxy.rule=Host(`traefik.localhost`)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - base-oauth

volumes:
  base-oauth-pg: null

networks:
  base-oauth:
    name: base-oauth
